# Generated by Django 4.0.6 on 2025-01-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EquiposDeTrabajo', '0005_rename_titulo_tarea_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='completada',
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('progreso', 'En progreso'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
    ]
