# Generated by Django 4.0.6 on 2025-01-03 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EquiposDeTrabajo', '0006_remove_tarea_completada_tarea_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
