# Generated by Django 4.0.6 on 2025-01-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EquiposDeTrabajo', '0007_tarea_asignado_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
