# Generated by Django 4.0.6 on 2025-01-04 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EquiposDeTrabajo', '0008_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EquiposDeTrabajo.usuario'),
        ),
    ]
