# Generated by Django 4.0.6 on 2025-01-04 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EquiposDeTrabajo', '0009_alter_tarea_asignado_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EquiposDeTrabajo.usuario'),
        ),
    ]
