# Generated by Django 4.0.6 on 2025-01-04 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EquiposDeTrabajo', '0010_proyecto_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='descripcion',
            field=models.TextField(default='Descripción por defecto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EquiposDeTrabajo.usuario'),
        ),
    ]
